import {
  Users,
  UserCheck,
  Briefcase,
  Layers,
  Database,
  ShieldCheck,
  Building2,
} from 'lucide-react';
import { Scenario, RoleTab } from './types';

export const UAT_SCENARIOS: Scenario[] = [
  // Staff Scenarios
  {
    id: 'STF-01',
    role: 'staff',
    title: 'Clock In GPS & Deteksi Geofence',
    steps: 'Buka halaman /clock-in. Izinkan GPS browser, pastikan koordinat terdeteksi dalam radius kantor.',
    expected: 'Status "Dalam Radius Kantor" hijau, tombol Clock In aktif dan submit berhasil menjadi auto_valid.',
    targetUrl: '/clock-in',
    actionLabel: 'Tes Clock In GPS',
  },
  {
    id: 'STF-02',
    role: 'staff',
    title: 'Catat Alasan Telat Aktual',
    steps: 'Buka /my-attendance. Temukan catatan presensi yang berstatus telat lalu klik "Isi Alasan".',
    expected: 'Modal input alasan muncul, alasan tersimpan tanpa memerlukan approval berbelit.',
    targetUrl: '/my-attendance',
    actionLabel: 'Buka Presensi Saya',
  },
  {
    id: 'STF-03',
    role: 'staff',
    title: 'Pengajuan Cuti Tahunan & Kuota 12 Hari',
    steps: 'Buka /requests, klik "Buat Pengajuan", pilih jenis "Cuti Tahunan", isi tanggal dan alasan.',
    expected: 'Sistem menampilkan sisa kuota cuti 12 hari dan pengajuan masuk ke status pending_spv.',
    targetUrl: '/requests',
    actionLabel: 'Buka Pengajuan Cuti',
  },
  {
    id: 'STF-04',
    role: 'staff',
    title: 'PWA Offline Attendance Queue',
    steps: 'Matikan koneksi WiFi/Data (DevTools Offline), lakukan Clock In di /clock-in.',
    expected: 'Banner offline muncul, presensi tersimpan di IndexedDB outbox dan sync saat koneksi pulih.',
    targetUrl: '/clock-in',
    actionLabel: 'Tes Mode Offline PWA',
  },
  {
    id: 'STF-05',
    role: 'staff',
    title: 'Lihat & Download Slip Gaji',
    steps: 'Buka /payroll pada tab "Slip Gaji Saya".',
    expected: 'Komponen gaji pokok, tunjangan, potongan absensi, dan PPh21 terinci rapi.',
    targetUrl: '/payroll',
    actionLabel: 'Cek Slip Gaji',
  },

  // SPV Scenarios
  {
    id: 'SPV-01',
    role: 'spv',
    title: 'Monitoring Presensi Tim Bawahan',
    steps: 'Buka /attendance-management (atau /dashboard). Filter data presensi berdasarkan tim divisi.',
    expected: 'Hanya anggota tim yang dipimpin yang tampil dalam rekapitulasi presensi harian.',
    targetUrl: '/attendance-management',
    actionLabel: 'Cek Presensi Tim',
  },
  {
    id: 'SPV-02',
    role: 'spv',
    title: 'Approval Pengajuan Cuti Anggota Tim',
    steps: 'Buka /approvals pada tab "Menunggu Persetujuan". Klik Review pada salah satu pengajuan bawahan.',
    expected: 'SPV dapat menyetujui (Approve) atau menolak (Reject) dengan catatan revisi.',
    targetUrl: '/approvals',
    actionLabel: 'Review Approval Tim',
  },
  {
    id: 'SPV-03',
    role: 'spv',
    title: 'Delegasi & Penugasan Lembur Tim',
    steps: 'Buka /overtime, klik "Buat Penugasan Lembur", pilih anggota tim bawahan dan estimasi jam.',
    expected: 'Surat Perintah Lembur (SPL) terbit dan bawahan menerima notifikasi penugasan.',
    targetUrl: '/overtime',
    actionLabel: 'Buka Menu Lembur',
  },

  // Kepala Divisi Scenarios
  {
    id: 'KDV-01',
    role: 'kepala_divisi',
    title: 'Approval Cuti Lintas Tim (Tingkat Dua)',
    steps: 'Buka /approvals dengan role Kepala Divisi. Periksa pengajuan yang telah diapprove oleh SPV.',
    expected: 'Pengajuan berstatus approved_spv membutuhkan sign-off Kepala Divisi sebelum ke HR.',
    targetUrl: '/approvals',
    actionLabel: 'Verifikasi Approval Kadiv',
  },
  {
    id: 'KDV-02',
    role: 'kepala_divisi',
    title: 'Monitoring KPI & Lembur Divisi',
    steps: 'Buka /reports, pilih filter divisi terkait, amati ringkasan jam lembur dan rasio absensi.',
    expected: 'Data analitik tersaring otomatis khusus divisi yang dipimpin.',
    targetUrl: '/reports',
    actionLabel: 'Buka Laporan Divisi',
  },

  // HR Administrator Scenarios
  {
    id: 'HR-01',
    role: 'hr',
    title: 'Import Batch File Presensi Fingerprint',
    steps: 'Buka /attendance-management tab "Import Fingerprint". Upload file Excel presensi Solution/ZKTeco.',
    expected: 'Pratinjau mapping AC No ke ID karyawan tampil, baris duplikat dihighlight, dan import tersimpan.',
    targetUrl: '/attendance-management',
    actionLabel: 'Tes Import Fingerprint',
  },
  {
    id: 'HR-02',
    role: 'hr',
    title: 'Review Presensi GPS Dinas Luar (Pending)',
    steps: 'Buka /attendance-management tab "Review GPS". Periksa clock-in di luar radius kantor.',
    expected: 'HR dapat melihat foto/koordinat dan menyetujui presensi dinas luar.',
    targetUrl: '/attendance-management',
    actionLabel: 'Buka Review GPS',
  },
  {
    id: 'HR-03',
    role: 'hr',
    title: 'Manajemen Kontrak PKWT & Database Karyawan',
    steps: 'Buka /employees. Pilih salah satu dari 94 karyawan hasil migrasi Odoo, klik tab "Kontrak".',
    expected: 'Detail profil lengkap, jabatan, NIK, dan opsi catat mutasi/perpanjangan kontrak aktif.',
    targetUrl: '/employees',
    actionLabel: 'Kelola Data Karyawan',
  },
  {
    id: 'HR-04',
    role: 'hr',
    title: 'Sinkronisasi Outbox ke Live Odoo ERP',
    steps: 'Buka /odoo-sync. Periksa status koneksi Odoo dan tekan tombol "Sync Sekarang".',
    expected: 'Koneksi ke kanti-sehati-sukses.odoo.com terhubung, item outbox dipush via JSON-RPC.',
    targetUrl: '/odoo-sync',
    actionLabel: 'Buka Sinkronisasi Odoo',
  },

  // Management / Direksi Scenarios
  {
    id: 'MGT-01',
    role: 'management',
    title: 'Kalkulasi Payroll & Aturan Lembur Kemenaker',
    steps: 'Buka /payroll tab "Periode Gaji". Buat periode berjalan dan klik "Hitung Otomatis".',
    expected: 'Perhitungan gaji pokok, lembur pengali 1.5x/2x, dan potongan absensi terhitung presisi.',
    targetUrl: '/payroll',
    actionLabel: 'Kalkulasi Payroll',
  },
  {
    id: 'MGT-02',
    role: 'management',
    title: 'Finalisasi & Lock Periode Penggajian',
    steps: 'Buka periode gaji yang telah dikaji, klik "Kunci & Finalisasi Periode".',
    expected: 'Periode terkunci (read-only), slip gaji resmi terdistribusi ke seluruh karyawan.',
    targetUrl: '/payroll',
    actionLabel: 'Finalisasi Gaji',
  },
  {
    id: 'MGT-03',
    role: 'management',
    title: 'Executive Analytics & Tren Biaya SDM',
    steps: 'Buka /reports tab "Executive Overview".',
    expected: 'Chart kehadiran, distribusi rasio lembur per departemen, dan tren absensi tampil interaktif.',
    targetUrl: '/reports',
    actionLabel: 'Buka Laporan Eksekutif',
  },

  // IT Administrator Scenarios
  {
    id: 'ADM-01',
    role: 'admin',
    title: 'System Health Probe & Latensi Database',
    steps: 'Buka /api/health untuk memeriksa diagnostik latency DB Supabase dan live Odoo connectivity.',
    expected: 'Response JSON status: "healthy", latency DB < 800ms, Odoo version 19.0+e.',
    targetUrl: '/api/health',
    actionLabel: 'Cek Health API',
  },
  {
    id: 'ADM-02',
    role: 'admin',
    title: 'Konfigurasi Master Kantor & Radius Geofence',
    steps: 'Buka /settings/offices. Pastikan lokasi kantor pusat terdaftar dengan lat/long & radius.',
    expected: 'Daftar kantor tersimpan dan menjadi acuan validasi geofence clock-in GPS.',
    targetUrl: '/settings/offices',
    actionLabel: 'Kelola Lokasi Kantor',
  },
  {
    id: 'ADM-03',
    role: 'admin',
    title: 'Audit Security Logs & RLS Integrity',
    steps: 'Buka /audit-logs. Amati pencatatan rekaman log seluruh mutasi sistem dan percobaan unauthorized.',
    expected: 'Setiap aksi penting tersimpan di audit_logs dengan timestamp, actor, dan changes_json.',
    targetUrl: '/audit-logs',
    actionLabel: 'Buka Audit Logs',
  },
];

export const ROLE_TABS: RoleTab[] = [
  { id: 'all', label: 'Semua Role', icon: Layers },
  { id: 'staff', label: 'Staff Karyawan', icon: Users },
  { id: 'spv', label: 'Supervisor (SPV)', icon: UserCheck },
  { id: 'kepala_divisi', label: 'Kepala Divisi', icon: Building2 },
  { id: 'hr', label: 'HR Administrator', icon: Briefcase },
  { id: 'management', label: 'Management / Direksi', icon: ShieldCheck },
  { id: 'admin', label: 'IT Administrator', icon: Database },
];
